version: '3.2'

services:
  loadbalancer:
    container_name: loadbalancer
    hostname: loadbalancer
    image: nginx:alpine
    restart: always
    volumes:
      - ./loadbalancer:/etc/nginx/conf.d
    ports:
      - 8000:80
    networks:
      - lb
    depends_on:
      - web1
      - web2
  web1:
    container_name: web1
    hostname: web1
    image: nginx:alpine
    restart: always
    volumes:
      - ./web1:/etc/nginx/conf.d
    ports:
      - 8001:80
    depends_on:
      - app
    networks:
      - lb
  web2:
    container_name: web2
    hostname: web2
    image: nginx:alpine
    restart: always
    volumes:
      - ./web2:/etc/nginx/conf.d
    ports:
      - 8002:80
    depends_on:
      - app
    networks:
      - lb
  app:
    container_name: app
    hostname: app
    build: ./app/
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./app/src/example:/var/www/example
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=example
      - DB_USERNAME=root
      - DB_PASSWORD=example
    networks: 
      - lb
  db:
    container_name: db
    image: mysql
    ports:
      - 8080:8080
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    networks:
      - lb

networks:
  lb:
