version: '3.2'

services:
  loadbalancer:
    container_name: "loadbalancer"
    image: nginx:alpine
    volumes:
      - ./loadbalancer:/etc/nginx/conf.d
    ports:
      - 8000:80
  web1:
    container_name: "web1"
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
    ports:
      - 8001:80
  web2:
    container_name: "web2"
    image: nginx:alpine
    volumes:
      - ./web2:/usr/share/nginx/html
    ports:
      - 8002:80
