version: '3.2'

services:
  loadbalancer:
    container_name: "loadbalancer"
    image: nginx:alpine
    volumes:
      - ./loadbalancer:/etc/nginx/conf.d
    ports:
      - 8000:80
    networks:
      - lb
    depends_on:
      - web1
      - web2
  web1:
    container_name: "web1"
    image: nginx:alpine
    ports:
      - 8001:80
    networks:
      - lb
  web2:
    container_name: "web2"
    image: nginx:alpine
    ports:
      - 8002:80
    networks:
      - lb
  phpfpm:
    container_name: "phpfpm"
    build: ./phpfpm/
    volumes:
      - ./src/sample:/var/www/sample
    ports:
      - 9000:9000
    environment:
      - DB_HOST=db
      - DB_DATABASE=example
      - DB_USERNAME=root
      - DB_PASSWORD=example
    networks: 
      - lb
  db:
    container_name: "db"
    image: mysql
    ports:
      - 8080:8080
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    networks:
      - lb

networks:
  lb:
